// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqDjmVnuXvWDTzzcDIM55mXBsu9mHb-NY',
    appId: '1:550012729362:web:46d103e990df07002500cb',
    messagingSenderId: '550012729362',
    projectId: 'e-commerce-project-9edeb',
    authDomain: 'e-commerce-project-9edeb.firebaseapp.com',
    storageBucket: 'e-commerce-project-9edeb.firebasestorage.app',
    measurementId: 'G-3DT715HPEK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCL-PeB0MLlS5VRdm19npe23DefozoD8fg',
    appId: '1:550012729362:android:fbf28673a98ec1222500cb',
    messagingSenderId: '550012729362',
    projectId: 'e-commerce-project-9edeb',
    storageBucket: 'e-commerce-project-9edeb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPsRDSyDMWhiQnRL_NY_yrDdEO0Y8q_Mw',
    appId: '1:550012729362:ios:cfd0698166bb10682500cb',
    messagingSenderId: '550012729362',
    projectId: 'e-commerce-project-9edeb',
    storageBucket: 'e-commerce-project-9edeb.firebasestorage.app',
    iosBundleId: 'com.example.eCommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPsRDSyDMWhiQnRL_NY_yrDdEO0Y8q_Mw',
    appId: '1:550012729362:ios:cfd0698166bb10682500cb',
    messagingSenderId: '550012729362',
    projectId: 'e-commerce-project-9edeb',
    storageBucket: 'e-commerce-project-9edeb.firebasestorage.app',
    iosBundleId: 'com.example.eCommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCqDjmVnuXvWDTzzcDIM55mXBsu9mHb-NY',
    appId: '1:550012729362:web:2e391263ffb40ad42500cb',
    messagingSenderId: '550012729362',
    projectId: 'e-commerce-project-9edeb',
    authDomain: 'e-commerce-project-9edeb.firebaseapp.com',
    storageBucket: 'e-commerce-project-9edeb.firebasestorage.app',
    measurementId: 'G-954LEBBF9C',
  );
}
